### ISSUE TITLE
[1.15.2] Error during the load_registries event phase: net.minecraft.item.Item$Properties.group(Lnet/minecraft/item/ItemGroup;)Lnet/minecraft/item/Item$Properties;

### ISSUE THREAD

**Issue by realTIMematrix** [MelanX/MoreVanillaTools#10]
Hi,

got issue while loading:

Using only this, no other mods.

Minecraft 1.15.2
Forge 31.0.1
morevanillatools-1.15.2-1.3.3.jar

Log: [latest.log](https://pastebin.com/U0rq0CGL)

Debug: [debug.log](https://pastebin.com/fn2WhcqL)

**Comment by MelanX** [comment]
Fixed and new version is available now. Deleted the old one because it was just a compiling mistake.
