### ISSUE TITLE
[1.15.2] Obsidean Pickaxe causing server to crash

### ISSUE THREAD

**Issue by TheMCmap** [MelanX/MoreVanillaTools#22]
I'm getting this error while using the Obsidean Pickaxe:

https://pastebin.com/k0TXjv0X

It had been working fine until I attempted to mine obsidean using Ore Excavator. Then after rebooting the server I attempted to mine obsidean without Ore Excavator and it still crashed.

**Comment by MelanX** [comment]
Mod version? Did you enchant the tool?

**Comment by TheMCmap** [comment]
No it was not enchanted. morevanillatools-1.15.2-2.0.2.jar

**Comment by MelanX** [comment]
Could you provide the complete crash log?

**Comment by TheMCmap** [comment]
https://pastebin.com/BCrathPN

**Comment by MelanX** [comment]
Is it a custom Modpack or one from curse?

**Comment by TheMCmap** [comment]
Yes, one I made myself. https://www.curseforge.com/minecraft/modpacks/mapcraft

**Comment by MelanX** [comment]
Okay, I'm looking into it tomorrow! Thank you for reporting

**Comment by TheMCmap** [comment]
I attempted to recreate the issue in single player and I couldn't.
