### ISSUE TITLE
Game crashes upon trying to enter or create a world

### ISSUE THREAD

**Issue by gatsuname-github** [MelanX/MoreVanillaTools#23]
I have both the Lib and MVT installed. This is a problem exclusively with MVT. I even disabled all my other mods to make sure there was no overlap. With only MVT and the Lib enabled, I am able to open to the title screen, go to the world select, and press play on a level. It shows "Reading world data..." and then "Saving World" then an immediate crash. the launcher shows "The game crashed whilst mouseclicked event handler Error: java.lang.ExceptionInInitializerError: null Exit Code: -1"
at first, i thought maybe my world was incompatible with the mod for some reason, so i decide to create a new one. immediately upon pressing "create new world" i get the same crash.

i DO NOT have this error with MVA. i DO NOT have this error with MVL. This is exclusively a MVT problem.

i would appreciate a swift reply, this mod looks fun and i would like to be able to use it.

**Comment by MelanX** [comment]
Provide crash log via pastebin and tell me the versions. Until that I will not read what you wrote above.

**Comment by gatsuname-github** [comment]
Forge 1.12.2 for Minecraft 1.16.2.
(This crash report does include my other mods, but I did test the game with only MVL, MVT, and Optifine)
https://pastebin.com/VZw1C9kU

i can provide logs with exclusively MVT MVL and Opti loaded if it is needed.

**Comment by gatsuname-github** [comment]
also, you should probably have some sort of outline for bug reports. nowhere on this mod does it state that i need to provide crash logs. i realize that it was probably pretty obvious to somebody with experience in modding like you but i really don't know much about mods - only installing them.

**Comment by MelanX** [comment]
Yes, that's true. I should add a template.
I tried with MoreVanillaTools 2.1.4 and MoreVanillaLib 1.2.12 on Forge 33.0.37 and there was no crash. Can you please try with only these two mods?

**Comment by MelanX** [comment]
Yes, that's true. I should add a template. Can you please try this without MoreVanillaArmor? Best would be just MoreVanillaTools and Lib. I think the problem is caused by MoreVanillaArmor.

**Comment by gatsuname-github** [comment]
i did try this without MVA, and the same issue still occured.

**Comment by MelanX** [comment]
Updating Forge to 33.0.54+ fixes the problem.
