### ISSUE TITLE
Resourse bug

### ISSUE THREAD

**Issue by kwadimwl** [MelanX/MoreVanillaTools#26]
Obsidian drops from all kinds of tools, added by mod.
I've tried to turn it off, and then on, so it had not helped.

**Comment by kwadimwl** [comment]
![image](https://user-images.githubusercontent.com/75992909/125123172-ff089680-e0fe-11eb-99b7-b62ab1a81cd5.png)
![image](https://user-images.githubusercontent.com/75992909/125123503-69213b80-e0ff-11eb-877f-e06d31586daf.png)

Chance of drop is 100%

**Comment by MelanX** [comment]
Problem solved with this: https://github.com/MelanX/MoreVanillaLib/issues/22
