### ISSUE TITLE
License change

### ISSUE THREAD

**Issue by MelanX** [MelanX/MoreVanillaTools#28]
I want to change to license from MIT License to Apache 2.0 License. More information can be found here: https://www.apache.org/licenses/LICENSE-2.0.txt

Before I change it, I need permissions from all contributors of this project. All the users below, do you agree the change to Apache 2.0?
- [x] @TheDirectorX 
- [x] d3ath9un (Discord)
- [x] SkyanUltra (CurseForge)

**Comment by TheDirectorX** [comment]
### I give permission. Do what needs to be done!
