### ISSUE TITLE
Hoes don't work

### ISSUE THREAD

**Issue by SirKrunk** [MelanX/MoreVanillaTools#30]
### Minecraft version

1.18.1

### MoreVanillaTools version

1.18.1-4.0.0

### Forge version

39.0.5

### The latest.log file

?

### Issue description

When right clicking dirt or grass with hoes, it doesn't get tilled

### Steps to reproduce

1. Right Click grass/dirt
2. does not get tilled

**Comment by MelanX** [comment]
Unfortunally, it's because Forge needs to re-implement this behaviour for hoes. I hope this will be done in near future.

**Comment by SirKrunk** [comment]
me too

**Comment by MelanX** [comment]
Made a workaround for now because I think that Forge will not fix this in near future. I hope it works in most situations.
You need to update MoreVanillaLib for this.

**Comment by SirKrunk** [comment]
what's a workaround?

**Comment by MelanX** [comment]
A fix which isn’t the "official" solution and will be removed once Forge fixed it. It may not work 100%

**Comment by SirKrunk** [comment]
Oh, ok
