### ISSUE TITLE
Mod Conflict or Mod Causing Server Crash

### ISSUE THREAD

**Issue by Camawama** [MelanX/MoreVanillaTools#9]
Hey there, my name is Alex and I have been trying to put together this Modpack for me and some friends to play on. Your mod works perfectly fine client-side but when running on a server it crashes and doesn't even load the world (like a few other mods I tried installing. I have put together a ZIP file with the Logs and the other mods installed with it (sadly the server froze up and I never got a crash report). I did this for every mod that caused the server to crash and I am contacting developers of the mods in hopes that it's enough information to diagnose the problems. I love to discover bugs and report them so if you ever need some help my discord is Cama#6274

Forge Version: Forge-30.0.39
Minecraft Version: 1.15.1

Here is the link: http://www.mediafire.com/file/9lcn2tp30azb2db/More_Vanilla_Tools.zip/file

**Comment by MelanX** [comment]
I can’t see anything in the logs. No exception, log just ending at world generation. I need more information to know if there is something wrong. 
I'm 99% sure that it’s not this mod.

**Comment by MelanX** [comment]
![F1CB3B4F-1855-42F2-83DB-E50D4FC86F30](https://user-images.githubusercontent.com/26039509/72588638-3e369c80-38f9-11ea-8243-e2aac8748131.jpeg)
Btw can't find you :) I think you should change your settings that everyone could find you

**Comment by Camawama** [comment]
Hey, sorry about the logs. I had to send this out for 5 different mods and didn't notice the logs were empty. I also didn't notice my privacy settings changed in discord. I am going to try and fix that right now so feel free to send a friend request. Once again sorry to bug you with little to no information on the problem.

I can't figure out my discord problem. I have never had this issed before
![Screenshot_20200117-004444_Discord](https://user-images.githubusercontent.com/43620900/72590086-969e7780-38c2-11ea-997a-473addc76873.jpg)

**Comment by Camawama** [comment]
If discord won't let you send a friend request is there a way I could dm you on GitHub?

**Comment by MelanX** [comment]
I don’t know if I do anything wrong... you could join my [Discord server](https://discord.chaotictrials.de/) and leave it after I found you.

**Comment by MelanX** [comment]
It's this: https://github.com/MelanX/MoreVanillaArmor/issues/2
